// Generated by scripts/generate-schema-sql.ts — do not edit.
// Final Prisma schema SQL for fresh database initialization.
export const SCHEMA_SQL = `
CREATE TABLE "Session" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "lastPreview" TEXT,
    "summary" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "endedAt" DATETIME
);

CREATE TABLE "Message" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sessionId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "rawInput" TEXT,
    "streamMeta" JSONB,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Message_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "Session" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "WebSetting" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'default',
    "streaming" BOOLEAN NOT NULL DEFAULT true,
    "model" TEXT,
    "ttsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "autoReadAssistant" BOOLEAN NOT NULL DEFAULT true,
    "ttsEngine" TEXT NOT NULL DEFAULT 'browser',
    "ttsVoice" TEXT,
    "ttsRate" REAL NOT NULL DEFAULT 1,
    "proactiveDailyEnabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

CREATE TABLE "UserPersona" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'default',
    "topicInterests" JSONB NOT NULL,
    "interactionPrefs" JSONB NOT NULL,
    "languageTrend" JSONB NOT NULL,
    "recentFocus" JSONB NOT NULL,
    "sourceStats" JSONB NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

CREATE TABLE "ProactiveDailyEvent" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "scheduledFor" DATETIME NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "processedAt" DATETIME,
    "sessionId" TEXT,
    "skipReason" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ProactiveDailyEvent_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "Session" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "DailyTopicRun" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "requestKey" TEXT NOT NULL,
    "runType" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "fallbackUsed" BOOLEAN NOT NULL DEFAULT false,
    "selectedTitle" TEXT NOT NULL,
    "selectedUrl" TEXT,
    "selectedSummary" TEXT,
    "queryKeywords" JSONB NOT NULL,
    "personaSnapshot" JSONB NOT NULL,
    "sessionId" TEXT,
    "eventId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DailyTopicRun_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "Session" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "DailyTopicRun_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "ProactiveDailyEvent" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "DailyTopicCandidate" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "runId" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "url" TEXT,
    "summary" TEXT,
    "publishedAt" DATETIME,
    "score" REAL,
    "selected" BOOLEAN NOT NULL DEFAULT false,
    "fallback" BOOLEAN NOT NULL DEFAULT false,
    "meta" JSONB,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DailyTopicCandidate_runId_fkey" FOREIGN KEY ("runId") REFERENCES "DailyTopicRun" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "Session_updatedAt_idx" ON "Session"("updatedAt");
CREATE INDEX "Message_sessionId_createdAt_idx" ON "Message"("sessionId", "createdAt");
CREATE UNIQUE INDEX "DailyTopicRun_requestKey_key" ON "DailyTopicRun"("requestKey");
CREATE INDEX "DailyTopicRun_runType_createdAt_idx" ON "DailyTopicRun"("runType", "createdAt");
CREATE INDEX "DailyTopicRun_sessionId_idx" ON "DailyTopicRun"("sessionId");
CREATE INDEX "DailyTopicRun_eventId_idx" ON "DailyTopicRun"("eventId");
CREATE INDEX "DailyTopicCandidate_runId_score_idx" ON "DailyTopicCandidate"("runId", "score");
CREATE INDEX "ProactiveDailyEvent_status_scheduledFor_idx" ON "ProactiveDailyEvent"("status", "scheduledFor");
CREATE INDEX "ProactiveDailyEvent_sessionId_idx" ON "ProactiveDailyEvent"("sessionId");
`.trim();
